version: "3.8"

services:
  api:
    command: >
      sh -c "npm run start:prod"
    depends_on:
      - db
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=usersdb
      - DATABASE_SYNC=true
      - POKEMON_API_URL=https://pokeapi.co/api/v2/pokemon
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
