# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1
orbs:
  node: circleci/node@6.2.0
  coveralls: coveralls/coveralls@2.2.5
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:24.9.0
        environment:
          DATABASE_HOST: 0.0.0.0
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: usersdb_test
          DATABASE_SYNC: true
          POKEMON_API_URL: https://pokeapi.co/api/v2/pokemon
          COVERALLS_REPO_TOKEN: 5tR9N9nixLEFhvDVyzHRd9AR4EW6DaklP
      #Service container image
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: usersdb_test
    executor: node/default

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: COVERALLS_REPO_TOKEN=5tR9N9nixLEFhvDVyzHRd9AR4EW6DaklP npm run test:cov
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .
      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  build_and_test_workflow:
    jobs:
      - build_and_test
